{% set name = "gcem" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kthohr/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 74cc499e2db247c32f1ce82fc22022d22e0f0a110ecd19281269289a9e78a6f8

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/gcem.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/gcem/gcemConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\gcem.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\gcemConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/kthohr/gcem
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'GCE-Math (Generalized Constant Expression Math): templated C++ library.'
  description: 'GCE-Math (Generalized Constant Expression Math): templated C++ library.'
  doc_url: https://gcem.readthedocs.io
  dev_url: https://github.com/kthohr/gcem

extra:
  recipe-maintainers:
    - tdegeus
